project_id = "diclwatocrixibjpajuf"

[auth]
enabled = true
site_url = "https://jenga-biz.vercel.app"
additional_redirect_urls = ["https://jenga-biz.vercel.app/auth", "https://jenga-biz.vercel.app/reset-password"]

[auth.email]
enable_confirmations = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-signup-confirmation]
verify_jwt = false
[functions.send-invite-confirmation]
verify_jwt = false
